version: "3.7"
services:
  
  #PLEX
  plex:
    container_name: plex
    image: plexinc/pms-docker
    network_mode: host
    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    
    limits:
      memory: 2048M

    environment:
      - TZ=Europe/Brussels 
      - PUID=1000
      - PGID=1000

    volumes:
      - /home/indy/docker/data/plex/config:/config
      - /home/indy/docker/data/plex/transcode:/transcode
      - /mnt/nfs:/data
      - /home/indy/certification:/certification

  #QBITTORRENT
  qbittorrent:
    container_name: qbittorrent
    image:  linuxserver/qbittorrent
  
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    limits:
      memory: 1024M

    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8181:8181"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - WEBUI_PORT=8181

    volumes:
      - /home/indy/docker/data/qbittorrent/config:/config
      - /mnt/nfs/downloads/complete:/torrents-complete
      - /mnt/nfs/downloads/incomplete:/torrents-incomplete

  #SONARR
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    limits:
      memory: 1524M

    ports:
      - "8989:8989"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/sonarr/config:/config 
      - /mnt/nfs/Tv:/tv 
      - /mnt/nfs/downloads/complete:/torrents-complete

  #RADARR
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    limits:
      memory: 1524M

    ports:
      - "7878:7878"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/radarr/config:/config 
      - /mnt/nfs/Movies:/movies 
      - /mnt/nfs/downloads/complete:/torrents-complete

  #JACKETT        limits:
          cpus: '0.50'
          memory: 50M
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    limits:
      memory: 1024M

    ports:
      - "9117:9117"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/jackett/config:/config
