version: "3"

volumes:
  #Local NAS
  nfs-all:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.12.200,nolock,soft,rw"
      device: ":/Multimedia/Videos/"

services:  
  #PLEX
  plex:
    container_name: plex
    image: plexinc/pms-docker
    network_mode: host
    restart: unless-stopped

    environment:
      - TZ=Europe/Brussels 
      - PUID=1000
      - PGID=1000

    volumes:
      - /home/indy/docker/data/plex/config:/config
      - /home/indy/docker/data/plex/transcode:/transcode
      - nfs:/data
      - /home/indy/certification:/certification

  #QBITTORRENT
  qbittorrent:
    container_name: qbittorrent
    image:  linuxserver/qbittorrent
    restart: unless-stopped

    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8181:8181"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - WEBUI_PORT=8181

    volumes:
      - /home/indy/docker/data/qbittorrent/config:/config
      - /mnt/nfs/downloads/complete:/torrents-complete
      - /mnt/nfs/downloads/incomplete:/torrents-incomplete

  #SONARR
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped

    ports:
      - "8989:8989"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/sonarr/config:/config 
      - nfs/Tv:/tv 
      - nfs/downloads/complete:/torrents-complete

  #RADARR
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped

    ports:
      - "7878:7878"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/radarr/config:/config 
      - nfs/Movies:/movies 
      - nfs/downloads/complete:/torrents-complete

  #JACKETT
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped

    ports:
      - "9117:9117"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/jackett/config:/config
