version: "3.7"
services:
  
  #PLEX
  plex:
    container_name: plex
    image: plexinc/pms-docker
    network_mode: host
    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 2048M
      
    environment:
      - TZ=Europe/Brussels 
      - PUID=1000
      - PGID=1000
      - PLEX_CLAIM="claim-pYVR5JbKTySqQgbNz5Ww"

    volumes:
      - /home/indy/docker/data/plex/config:/config
      - /home/indy/docker/data/plex/transcode:/transcode
      - /mnt/nfs:/data
      - /home/indy/certification:/certification

  #SABNZBD
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/sabnzbd/config:/config
      - /home/indy/docker/data/sabnzbd/downloads:/downloads-complete 
      - /home/indy/docker/data/sabnzbd/incomplete-downloads:/downloads-incomplete

  #QBITTORRENT
  qbittorrent:
    container_name: qbittorrent
    image:  linuxserver/qbittorrent
  
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1024M

    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8181:8181"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - WEBUI_PORT=8181

    volumes:
      - /home/indy/docker/data/qbittorrent/config:/config
      - /home/indy/docker/data/qbittorrent/downloads:/torrents-complete
      - /home/indy/docker/data/qbittorrent/incomplete-downloads:/torrents-incomplete

  #SONARR
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1524M

    ports:
      - "8989:8989"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/sonarr/config:/config 
      - /mnt/nfs/Tv:/tv 
      - /home/indy/docker/data/sabnzbd/downloads:/downloads-complete
      - /home/indy/docker/data/qbittorrent/downloads:/torrents-complete

  #RADARR
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1524M

    ports:
      - "7878:7878"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/radarr/config:/config 
      - /mnt/nfs/Movies:/movies 
      - /home/indy/docker/data/sabnzbd/downloads:/downloads-complete
      - /home/indy/docker/data/qbittorrent/downloads:/torrents-complete

  #JACKETT
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1024M

    ports:
      - "9117:9117"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/jackett/config:/config
