version: "3"
services:

  #SABNZBD
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/sabnzbd/config:/config
      - /home/indy/docker/data/sabnzbd/downloads:/downloads 
      - /home/indy/docker/data/sabnzbd/incomplete-downloads:/incomplete-downloads


  #SONARR
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped

    ports:
      - "8989:8989"

    depends_on:
      - sabnzbd

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/sonarr/config:/config 
      - /mnt/nfs/Tv:/tv 
      - /home/indy/docker/data/sabnzbd/downloads:/downloads

  #RADARR
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped

    ports:
      - "7878:7878"

    depends_on:
      - sabnzbd

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

    volumes:
      - /home/indy/docker/data/radarr/config:/config 
      - /mnt/nfs/Movies:/movies 
      - /home/indy/docker/data/sabnzbd/downloads:/downloads
